version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health_bot
    env_file:
      - .env
    environment:
      POSTGRES_DSN: postgresql+asyncpg://admin:pass@host.docker.internal:5432/health_bot
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - health_bot_network

networks:
  health_bot_network:
